### ISSUE TITLE
Content Strategy and Content Inventory

### ISSUE THREAD

**Issue by jaybeebauer** [jaybeebauer/codefair#12]
What is the key content that your website should communicate?
What is the key function your website should perform?
What will your web visitors remember about your site (your brand)?

you need to review the content provided by the client, catalogue what exists and determine what else you might need to achieve the content strategy.

Develop your own definition of a content inventory

With your partner/s, inventory your existing content:  
use the spreadsheet opposite to create your own inventory (adapt),
detail the resources you currently have, and
detail the resources that you think you may still require

**Comment by jaybeebauer** [comment]
Content Strategy and Inventory are "done" just waiting on your response, I'm also waiting on the actual template from Barbara

**Comment by krisbebb** [comment]
Reviewed strategy and inventory. 
Good work, I have nothing to add.

**Comment by krisbebb** [comment]
Adding some points from 2016 Code Fair report to Content Strategy.
Adding "files" column for content inventory. Reviewing docs / imgs provided.

**Comment by krisbebb** [comment]
Content strategy additions are in original file Content Strategy.docx (Highlighted in red).
Keep them, or edit as you see fit.
I added heaps of stuff to the Content Inventory spreadsheet (I made a duplicate because the numbering was getting messy). Additions highlighted in yellow. I am not attached to adding more material, just trying to tie in some information from Report 2016 suggestions.

Hope I haven't made this heaps more work than it needs to be.
